services:
  - type: web
    name: stockroom-ecommerce
    env: node
    plan: free
    buildCommand: cd backend && npm install --include=dev && npm run build && cd ../frontend && npm install --include=dev && npm run build
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_VERSION
        value: "20"
